name: vigilant
description: Official Dart SDK for the Vigilant platform
version: 1.0.0
homepage: https://github.com/vigilant-run/vigilant-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
