name: Publish to pub.dev

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test

      - name: Analyze
        run: dart analyze

      - name: Setup Pub Credentials
        env:
          PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken": "${PUB_DEV_PUBLISH_ACCESS_TOKEN}",
            "refreshToken": "${PUB_DEV_PUBLISH_REFRESH_TOKEN}",
            "tokenEndpoint": "https://accounts.google.com/o/oauth2/token",
            "scopes": ["openid", "https://www.googleapis.com/auth/userinfo.email"],
            "expiration": 1697055824
          }
          EOF

      - name: Publish package
        run: dart pub publish
